dist: xenial
language: minimal

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - deploy

env:
# Carefull, also set it in the deploy section!
- NOTES_FILE=main

services:
- docker

script:
- docker run --rm -v $(pwd):/notes blang/latex /bin/bash -c "cd /notes; ./build.sh $NOTES_FILE"
- "./test.sh $NOTES_FILE"

deploy:
  provider: releases
  api_key:
    secure: AF9baAPXzZ2ANpPW7LMNeLohXnIle5H8xQe3CaWspxu8zf3y2AqEEhG4oB5b176vdn4jaYivY1xLdsnc/AKFPRuQg35mBHVcez95VmhTCu4O5HENhkXW1FGvvwgJiH5dDGPDttOr5uYEobw/kwkKC4XuAkIFEFickjczY7WRYpX2PJCL0Uo7J/TwDxo5iQVs4dYJFDSRLPG1IfVYvXfkrey6U+OqtzqvglBvY9IQkNt316Oxw9tXhLC//7Rj7zFoDQcOfvjRm9HjDmMZfSmdrJPwaqgPjds4GdmLTz/9Qd5G6yP3X7HYGk0KrRnOayIE7j8/tXGuO96zOLfqc+3BnUwrvs29gNQrk2ClwTblw0A8tqlabFe48QLDq2esibMgGfXoqUNvaZ7pL9EVVj9lWG/VV4X4BzldgqXvrCGf2VC0aAFiLfhP5L8Hn7rffXQE6mhkwdmTLljp2Vps7xC2Dkl6GL7IAbpwWC/FkwH6kp4Rp/61JGAY9MCcyiPJgAft2CCinWfQKP13YHUTXuQ2ILoj1HYjJRO6HS/Kltx+dy24nMnkvOT0uz6h8I1sxo+sxavY+kmCAJ0L45w9eGhIrMa9tAIMfJyB5laWuEPtlunXVUrIeEFiLhebccFd8fnNTBbePNaYGWoMS0+2UsXFe7dvNCCIBgNJFLPT160/sKg=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: icl-notes/m1j1
